[tool.poetry]
name = "gimie"
version = "0.1.0"
description = "Extract structured metadata from git repositories."
authors = ["cmdoret <cyril.mattheydoret@gmail.com>"]
license = "GPLv3"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.7"
extruct = "^0.14.0"
PyDriller = "^2.3"

[tool.poetry.group.dev.dependencies]
pytest = "^7.2.0"
black = "^22.10.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
