name: Conventional PR title
on:
  pull_request_target:
    types:
      - opened
      - reopened
      - edited
      - synchronize

jobs:
  title-format:
    runs-on: ubuntu-latest
    steps:
      # https://github.com/amannn/action-semantic-pull-request
      - name: PR title format check
        uses: amannn/action-semantic-pull-request@v5.3.0
        continue-on-error: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          validateSingleCommit: true
