name: Python package
on:
  push:
    tags:
      - "v*.*.*"
jobs:
  tests:
    uses: ./.github/workflows/poetry-pytest.yml
  build:
    runs-on: ubuntu-latest
    steps:
      - needs: [tests]
      - uses: actions/checkout@v2
      - name: Build and publish to pypi
        uses: JRubics/poetry-publish@v1.16
        with:
          pypi_token: ${{ secrets.PYPI_TOKEN }}
          repository_name: "testpypi"
          repository_url: "https://test.pypi.org/legacy/"
