name: tests

on: [push]

jobs:

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 0

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Poetry
        uses: snok/install-poetry@v1

      - name: Install Dependencies
        run: poetry install
        if: steps.cache.outputs.cache-hit != 'true'

      - name: Code Quality
        run: poetry run black . --check

      - name: Test with pytest
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_GITHUB_TOKEN }}
          GITLAB_TOKEN: ${{ secrets.GITLAB_ACCESS_TOKEN }}
        run: make test

      - name: Upload coverage report
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.ACCESS_GITHUB_TOKEN }}
          GITLAB_TOKEN: ${{ secrets.GITLAB_ACCESS_TOKEN }}
          COVERALLS_PARALLEL: true
        run: coveralls --service=github-actions
        continue-on-error: true
